---
name: Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: Setup packages
        shell: bash
        run :
          sudo apt-get install ninja-build

      - name: CMake Setup
        working-directory: build
        shell: bash
        run: |
          cmake .. -G Ninja

      - name: Build
        working-directory: build
        shell: bash
        run: |
          cmake --build . --config Release --target all

      - name: Package
        working-directory: build
        shell: bash
        run: |
          cpack -G DEB
      - uses: actions/upload-artifact@v4
        with:
          name: Installers
          path: |
            build/*.deb

      #   working-directory: build
      #   shell: bash
      #   run: |
      #     curl -L -O http://131.123.42.41/srcml_1.0.0-1_ubuntu22.04_x86_64.deb
      #     sudo apt-get install ./srcml*.deb

      # - name: Test
      #   working-directory: build
      #   shell: bash
      #   continue-on-error: true
      #   run: |
      #     ctest --verbose | tee TestResults.log
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: Test.${{matrix.os}}.log
      #     path: |
      #       build/Testing/Temporary/LastTest.log
      #       build/TestResults.log
